version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11-browsers
    steps:
      - checkout
      - restore_cache:
          key: -v3-{{ checksum "yarn.lock" }}
      - run: 
          name: Install dependencies
          command: yarn
      - save_cache:
          key: -v3-{{ checksum "yarn.lock" }}
          paths:
            - "yarn.lock"
            - "node_modules"
      - run:
          name: Test
          command: yarn jest
      - run:
          name: Codecov
          command: yarn codecov
workflows:
  version: 2
  tests:
    jobs:
      - test